site_name: OpenShift 5 Virtualization Lab
docs_dir: publishing-house/spec
nav:
- Home: index.md
- Design Spec: design.md
- Modules:
  - Module 1 - Intro: modules/module-01-intro.md
  - Module 2 - Vm Management: modules/module-02-vm-management.md
  - Module 3 - Migration: modules/module-03-migration.md
  - Module 4 - Storage: modules/module-04-storage.md
  - Module 5 - Backup Recovery: modules/module-05-backup-recovery.md
  - Module 6 - Templates: modules/module-06-templates.md
  - Module 7 - Networking: modules/module-07-networking.md
  - Module 8 - Vms And Apps: modules/module-08-vms-and-apps.md
plugins:
- techdocs-core
