---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: shared-resource-viewer
  namespace: openshift
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: 'false'
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
      - template.openshift.io
    resources:
      - templates
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
      - image.openshift.io
    resources:
      - imagestreamimages
      - imagestreams
      - imagestreamtags
      - imagetags
  - verbs:
      - get
    apiGroups:
      - ''
      - image.openshift.io
    resources:
      - imagestreams/layers
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - configmaps
  - verbs:
      - create
    apiGroups:
      - template.openshift.io
    resources:
      - processedtemplates
